<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.3" />
    <PackageReference Include="QuestPDF" Version="2025.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VenuePlatform.BLL\VenuePlatform.BLL.csproj" />
    <ProjectReference Include="..\VenuePlatform.Contracts\VenuePlatform.Contracts.csproj" />
    <ProjectReference Include="..\VenuePlatform.DAL\VenuePlatform.DAL.csproj" />
  </ItemGroup>

</Project>
