<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        <PackageReference Include="NetArchTest.Rules" Version="1.3.2" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.8" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Tests.Shared\Tests.Shared.csproj" />
        <ProjectReference Include="..\Users.Application\Users.Application.csproj" />
        <ProjectReference Include="..\Users.Domain\Users.Domain.csproj" />
        <ProjectReference Include="..\Users.Infrastructure\Users.Infrastructure.csproj" />
        <ProjectReference Include="..\Users.Web\Users.Web.csproj" />
        <ProjectReference Include="..\Modules.SharedKernel\Modules.SharedKernel.csproj" />
        <ProjectReference Include="..\Base.Helpers\Base.Helpers.csproj" />
        <ProjectReference Include="..\WebApp\WebApp.csproj" />
    </ItemGroup>

</Project>
