//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views.Orders {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {

        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() { }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    resourceMan = new System.Resources.ResourceManager("App.Resources.Views.Orders.Index", typeof(Index).Assembly);
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string MyOrders { get { return ResourceManager.GetString("MyOrders", resourceCulture); } }
        public static string NoOrders { get { return ResourceManager.GetString("NoOrders", resourceCulture); } }
        public static string StartShopping { get { return ResourceManager.GetString("StartShopping", resourceCulture); } }
        public static string OrderNumber { get { return ResourceManager.GetString("OrderNumber", resourceCulture); } }
        public static string Date { get { return ResourceManager.GetString("Date", resourceCulture); } }
        public static string Items { get { return ResourceManager.GetString("Items", resourceCulture); } }
        public static string Total { get { return ResourceManager.GetString("Total", resourceCulture); } }
        public static string Status { get { return ResourceManager.GetString("Status", resourceCulture); } }
        public static string View { get { return ResourceManager.GetString("View", resourceCulture); } }
    }
}
