//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Base.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ErrorMessage_MaxLength {
            get {
                return ResourceManager.GetString("ErrorMessage_MaxLength", resourceCulture);
            }
        }
        
        public static string ErrorMessage_MinLength {
            get {
                return ResourceManager.GetString("ErrorMessage_MinLength", resourceCulture);
            }
        }
        
        public static string ErrorMessage_Required {
            get {
                return ResourceManager.GetString("ErrorMessage_Required", resourceCulture);
            }
        }
        
        public static string ErrorMessage_StringLengthMax {
            get {
                return ResourceManager.GetString("ErrorMessage_StringLengthMax", resourceCulture);
            }
        }
        
        public static string ErrorMessage_StringLengthMinMax {
            get {
                return ResourceManager.GetString("ErrorMessage_StringLengthMinMax", resourceCulture);
            }
        }
        
        public static string ErrorMessage_Range {
            get {
                return ResourceManager.GetString("ErrorMessage_Range", resourceCulture);
            }
        }
        
        public static string ErrorMessage_ValueIsInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_ValueIsInvalid", resourceCulture);
            }
        }
        
        public static string ErrorMessage_AttemptedValueIsInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_AttemptedValueIsInvalid", resourceCulture);
            }
        }
        
        public static string ErrorMessage_MissingBindRequiredValue {
            get {
                return ResourceManager.GetString("ErrorMessage_MissingBindRequiredValue", resourceCulture);
            }
        }
        
        public static string ErrorMessage_MissingKeyOrValue {
            get {
                return ResourceManager.GetString("ErrorMessage_MissingKeyOrValue", resourceCulture);
            }
        }
        
        public static string ErrorMessage_MissingRequestBodyRequiredValue {
            get {
                return ResourceManager.GetString("ErrorMessage_MissingRequestBodyRequiredValue", resourceCulture);
            }
        }
        
        public static string ErrorMessage_NonPropertyAttemptedValueIsInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_NonPropertyAttemptedValueIsInvalid", resourceCulture);
            }
        }
        
        public static string ErrorMessage_NonPropertyUnknownValueIsInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_NonPropertyUnknownValueIsInvalid", resourceCulture);
            }
        }
        
        public static string ErrorMessage_NonPropertyValueMustBeANumber {
            get {
                return ResourceManager.GetString("ErrorMessage_NonPropertyValueMustBeANumber", resourceCulture);
            }
        }
        
        public static string ErrorMessage_UnknownValueIsInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_UnknownValueIsInvalid", resourceCulture);
            }
        }
        
        public static string ErrorMessage_ValueMustBeANumber {
            get {
                return ResourceManager.GetString("ErrorMessage_ValueMustBeANumber", resourceCulture);
            }
        }
        
        public static string ErrorMessage_ValueMustNotBeNull {
            get {
                return ResourceManager.GetString("ErrorMessage_ValueMustNotBeNull", resourceCulture);
            }
        }
        
        public static string ErrorMessage_NotValidPhone {
            get {
                return ResourceManager.GetString("ErrorMessage_NotValidPhone", resourceCulture);
            }
        }
        
        public static string Form_Cancel {
            get {
                return ResourceManager.GetString("Form_Cancel", resourceCulture);
            }
        }
        
        public static string Form_Save {
            get {
                return ResourceManager.GetString("Form_Save", resourceCulture);
            }
        }
        
        public static string Form_DropDownSelect {
            get {
                return ResourceManager.GetString("Form_DropDownSelect", resourceCulture);
            }
        }
        
        public static string Form_BackToList {
            get {
                return ResourceManager.GetString("Form_BackToList", resourceCulture);
            }
        }
        
        public static string Form_Edit {
            get {
                return ResourceManager.GetString("Form_Edit", resourceCulture);
            }
        }
        
        public static string Form_Details {
            get {
                return ResourceManager.GetString("Form_Details", resourceCulture);
            }
        }
        
        public static string Form_Delete {
            get {
                return ResourceManager.GetString("Form_Delete", resourceCulture);
            }
        }
        
        public static string Form_Create {
            get {
                return ResourceManager.GetString("Form_Create", resourceCulture);
            }
        }
        
        public static string Form_Search {
            get {
                return ResourceManager.GetString("Form_Search", resourceCulture);
            }
        }
        
        public static string Form_Clear {
            get {
                return ResourceManager.GetString("Form_Clear", resourceCulture);
            }
        }
        
        public static string Form_Actions {
            get {
                return ResourceManager.GetString("Form_Actions", resourceCulture);
            }
        }
        
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
