services:
  assignment1:
    build:
      context: ./JS/assignment1
      dockerfile: Dockerfile
    ports:
      - "3001:80"

  assignment2:
    build:
      context: ./JS/assignment2
      dockerfile: Dockerfile
    ports:
      - "3002:80"