//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views.Home {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {

        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() { }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    resourceMan = new System.Resources.ResourceManager("App.Resources.Views.Home.Index", typeof(Index).Assembly);
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string HeroTitle { get { return ResourceManager.GetString("HeroTitle", resourceCulture); } }
        public static string HeroSubtitle { get { return ResourceManager.GetString("HeroSubtitle", resourceCulture); } }
        public static string ShopNow { get { return ResourceManager.GetString("ShopNow", resourceCulture); } }
        public static string Collections { get { return ResourceManager.GetString("Collections", resourceCulture); } }
        public static string ViewCollection { get { return ResourceManager.GetString("ViewCollection", resourceCulture); } }
        public static string FeaturedProducts { get { return ResourceManager.GetString("FeaturedProducts", resourceCulture); } }
        public static string ViewAll { get { return ResourceManager.GetString("ViewAll", resourceCulture); } }
        public static string ShopByCategory { get { return ResourceManager.GetString("ShopByCategory", resourceCulture); } }
        public static string From { get { return ResourceManager.GetString("From", resourceCulture); } }
        public static string NoImage { get { return ResourceManager.GetString("NoImage", resourceCulture); } }
    }
}
