//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views.Orders {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Detail {

        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Detail() { }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    resourceMan = new System.Resources.ResourceManager("App.Resources.Views.Orders.Detail", typeof(Detail).Assembly);
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string MyOrders { get { return ResourceManager.GetString("MyOrders", resourceCulture); } }
        public static string Order { get { return ResourceManager.GetString("Order", resourceCulture); } }
        public static string Placed { get { return ResourceManager.GetString("Placed", resourceCulture); } }
        public static string Items { get { return ResourceManager.GetString("Items", resourceCulture); } }
        public static string Product { get { return ResourceManager.GetString("Product", resourceCulture); } }
        public static string Variant { get { return ResourceManager.GetString("Variant", resourceCulture); } }
        public static string Qty { get { return ResourceManager.GetString("Qty", resourceCulture); } }
        public static string UnitPrice { get { return ResourceManager.GetString("UnitPrice", resourceCulture); } }
        public static string Total { get { return ResourceManager.GetString("Total", resourceCulture); } }
        public static string ShippingAddress { get { return ResourceManager.GetString("ShippingAddress", resourceCulture); } }
    }
}
