//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views.Cart {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {

        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() { }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    resourceMan = new System.Resources.ResourceManager("App.Resources.Views.Cart.Index", typeof(Index).Assembly);
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string YourCart { get { return ResourceManager.GetString("YourCart", resourceCulture); } }
        public static string CartEmpty { get { return ResourceManager.GetString("CartEmpty", resourceCulture); } }
        public static string ContinueShopping { get { return ResourceManager.GetString("ContinueShopping", resourceCulture); } }
        public static string Product { get { return ResourceManager.GetString("Product", resourceCulture); } }
        public static string Variant { get { return ResourceManager.GetString("Variant", resourceCulture); } }
        public static string Price { get { return ResourceManager.GetString("Price", resourceCulture); } }
        public static string Qty { get { return ResourceManager.GetString("Qty", resourceCulture); } }
        public static string Total { get { return ResourceManager.GetString("Total", resourceCulture); } }
        public static string Update { get { return ResourceManager.GetString("Update", resourceCulture); } }
        public static string Remove { get { return ResourceManager.GetString("Remove", resourceCulture); } }
        public static string OrderSummary { get { return ResourceManager.GetString("OrderSummary", resourceCulture); } }
        public static string Items { get { return ResourceManager.GetString("Items", resourceCulture); } }
        public static string ProceedToCheckout { get { return ResourceManager.GetString("ProceedToCheckout", resourceCulture); } }
    }
}
