<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.AspNetCore.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sales.Application\Sales.Application.csproj" />
    <ProjectReference Include="..\Sales.Domain\Sales.Domain.csproj" />
    <ProjectReference Include="..\Modules.Contracts\Modules.Contracts.csproj" />
    <ProjectReference Include="..\Modules.SharedKernel\Modules.SharedKernel.csproj" />
    <ProjectReference Include="..\App.Resources\App.Resources.csproj" />
    <ProjectReference Include="..\App.DTO\App.DTO.csproj" />
  </ItemGroup>

</Project>
