<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Update="Views\Shared\_Layout.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>_Layout.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Home\Index.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Index.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Shop\Index.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Index.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Shop\Detail.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Detail.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Cart\Index.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Index.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Orders\Index.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Index.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Orders\Detail.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Detail.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\Shared\_Layout.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>_Layout.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Home\Index.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Index.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Shop\Index.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Index.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Shop\Detail.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Detail.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Cart\Index.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Index.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Orders\Index.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Index.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Orders\Detail.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Detail.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
