<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Base.Contracts\Base.Contracts.csproj" />
    <ProjectReference Include="..\Base.Domain\Base.Domain.csproj" />
    <ProjectReference Include="..\Base.DAL.Contracts\Base.DAL.Contracts.csproj" />
  </ItemGroup>

</Project>
