services:
  webapp-taltech:
    build: .
    container_name: webapp-taltech
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=com-akaver-taltech;Username=postgres;Password=postgres"
    networks:
      - infra

  vue-app:
    build:
      context: ./vue-app
      args:
        VITE_API_BASE_URL: https://taltech.akaver.com
    container_name: vue-app-taltech
    restart: unless-stopped
    ports:
      - "77:80"
    networks:
      - infra

networks:
  infra:
    name: infra
    external: true
