<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <UserSecretsId>aspnet-WebApp-3E2C379D-18DC-42FC-8ACE-F3CD6804F127</UserSecretsId>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>
    
    <ItemGroup>
        <!--
        <PackageReference Include="com.akaver.Extensions" Version="1.1.0" />
        -->

        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\App.DAL.EF\App.DAL.EF.csproj" />
      <ProjectReference Include="..\com.akaver.Extensions\com.akaver.Extensions.csproj" />
      <ProjectReference Include="..\PublicApi.DTO.v1\PublicApi.DTO.v1.csproj" />
      <ProjectReference Include="..\Resources\Resources.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Areas" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\Temi\Contact.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Temi\Index.cshtml" />
    </ItemGroup>

</Project>
