//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views.Shop {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Detail {

        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Detail() { }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    resourceMan = new System.Resources.ResourceManager("App.Resources.Views.Shop.Detail", typeof(Detail).Assembly);
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string Shop { get { return ResourceManager.GetString("Shop", resourceCulture); } }
        public static string NoImage { get { return ResourceManager.GetString("NoImage", resourceCulture); } }
        public static string SelectVariant { get { return ResourceManager.GetString("SelectVariant", resourceCulture); } }
        public static string Material { get { return ResourceManager.GetString("Material", resourceCulture); } }
        public static string Color { get { return ResourceManager.GetString("Color", resourceCulture); } }
        public static string Size { get { return ResourceManager.GetString("Size", resourceCulture); } }
        public static string InStock { get { return ResourceManager.GetString("InStock", resourceCulture); } }
        public static string Left { get { return ResourceManager.GetString("Left", resourceCulture); } }
        public static string OutOfStock { get { return ResourceManager.GetString("OutOfStock", resourceCulture); } }
        public static string AddToCart { get { return ResourceManager.GetString("AddToCart", resourceCulture); } }
        public static string LoginToPurchase { get { return ResourceManager.GetString("LoginToPurchase", resourceCulture); } }
    }
}
