//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views.Public {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pages {

        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Pages() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager => resourceMan ??= new System.Resources.ResourceManager("App.Resources.Views.Public.Pages", typeof(Pages).Assembly);

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string BrandName => ResourceManager.GetString("BrandName", resourceCulture);
        public static string LandingTitle => ResourceManager.GetString("LandingTitle", resourceCulture);
        public static string NavHome => ResourceManager.GetString("NavHome", resourceCulture);
        public static string NavBrowseVenues => ResourceManager.GetString("NavBrowseVenues", resourceCulture);
        public static string NavRequestVenue => ResourceManager.GetString("NavRequestVenue", resourceCulture);
        public static string NavLogin => ResourceManager.GetString("NavLogin", resourceCulture);
        public static string NavRegister => ResourceManager.GetString("NavRegister", resourceCulture);
        public static string NavWorkspace => ResourceManager.GetString("NavWorkspace", resourceCulture);
        public static string LandingEyebrow => ResourceManager.GetString("LandingEyebrow", resourceCulture);
        public static string LandingHeadline => ResourceManager.GetString("LandingHeadline", resourceCulture);
        public static string LandingDescription => ResourceManager.GetString("LandingDescription", resourceCulture);
        public static string LandingPrimaryCta => ResourceManager.GetString("LandingPrimaryCta", resourceCulture);
        public static string LandingSecondaryCta => ResourceManager.GetString("LandingSecondaryCta", resourceCulture);
        public static string LandingMetricVenues => ResourceManager.GetString("LandingMetricVenues", resourceCulture);
        public static string LandingMetricCities => ResourceManager.GetString("LandingMetricCities", resourceCulture);
        public static string LandingMetricBookings => ResourceManager.GetString("LandingMetricBookings", resourceCulture);
        public static string LandingFeaturedHeading => ResourceManager.GetString("LandingFeaturedHeading", resourceCulture);
        public static string LandingFeaturedDescription => ResourceManager.GetString("LandingFeaturedDescription", resourceCulture);
        public static string LandingFeatureOneTitle => ResourceManager.GetString("LandingFeatureOneTitle", resourceCulture);
        public static string LandingFeatureOneBody => ResourceManager.GetString("LandingFeatureOneBody", resourceCulture);
        public static string LandingFeatureTwoTitle => ResourceManager.GetString("LandingFeatureTwoTitle", resourceCulture);
        public static string LandingFeatureTwoBody => ResourceManager.GetString("LandingFeatureTwoBody", resourceCulture);
        public static string LandingFeatureThreeTitle => ResourceManager.GetString("LandingFeatureThreeTitle", resourceCulture);
        public static string LandingFeatureThreeBody => ResourceManager.GetString("LandingFeatureThreeBody", resourceCulture);
        public static string LandingFeatureSectionTitle => ResourceManager.GetString("LandingFeatureSectionTitle", resourceCulture);
        public static string BrowseTitle => ResourceManager.GetString("BrowseTitle", resourceCulture);
        public static string BrowseEyebrow => ResourceManager.GetString("BrowseEyebrow", resourceCulture);
        public static string BrowseHeadline => ResourceManager.GetString("BrowseHeadline", resourceCulture);
        public static string BrowseDescription => ResourceManager.GetString("BrowseDescription", resourceCulture);
        public static string BrowsePrimaryCta => ResourceManager.GetString("BrowsePrimaryCta", resourceCulture);
        public static string BrowseEmpty => ResourceManager.GetString("BrowseEmpty", resourceCulture);
        public static string VenueFromRate => ResourceManager.GetString("VenueFromRate", resourceCulture);
        public static string VenueHourlyUnit => ResourceManager.GetString("VenueHourlyUnit", resourceCulture);
        public static string VenueCapacityLabel => ResourceManager.GetString("VenueCapacityLabel", resourceCulture);
        public static string VenueSpacesLabel => ResourceManager.GetString("VenueSpacesLabel", resourceCulture);
        public static string VenueBookingsLabel => ResourceManager.GetString("VenueBookingsLabel", resourceCulture);
        public static string VenueAddressLabel => ResourceManager.GetString("VenueAddressLabel", resourceCulture);
        public static string VenueViewSpacesCta => ResourceManager.GetString("VenueViewSpacesCta", resourceCulture);
        public static string VenueDetailsTitle => ResourceManager.GetString("VenueDetailsTitle", resourceCulture);
        public static string VenueDetailsEyebrow => ResourceManager.GetString("VenueDetailsEyebrow", resourceCulture);
        public static string VenueDetailsFallbackDescription => ResourceManager.GetString("VenueDetailsFallbackDescription", resourceCulture);
        public static string VenueDetailsBackToBrowse => ResourceManager.GetString("VenueDetailsBackToBrowse", resourceCulture);
        public static string VenueDetailsOverviewTitle => ResourceManager.GetString("VenueDetailsOverviewTitle", resourceCulture);
        public static string VenueDetailsSpacesTitle => ResourceManager.GetString("VenueDetailsSpacesTitle", resourceCulture);
        public static string VenueDetailsSpacesDescription => ResourceManager.GetString("VenueDetailsSpacesDescription", resourceCulture);
        public static string VenueDetailsSpacesEmpty => ResourceManager.GetString("VenueDetailsSpacesEmpty", resourceCulture);
        public static string VenueSpaceMinimumDurationLabel => ResourceManager.GetString("VenueSpaceMinimumDurationLabel", resourceCulture);
        public static string VenueSpaceStatusLabel => ResourceManager.GetString("VenueSpaceStatusLabel", resourceCulture);
        public static string VenueSpaceMinutesValue => ResourceManager.GetString("VenueSpaceMinutesValue", resourceCulture);
        public static string RequestTitle => ResourceManager.GetString("RequestTitle", resourceCulture);
        public static string RequestEyebrow => ResourceManager.GetString("RequestEyebrow", resourceCulture);
        public static string RequestHeadline => ResourceManager.GetString("RequestHeadline", resourceCulture);
        public static string RequestDescription => ResourceManager.GetString("RequestDescription", resourceCulture);
        public static string RequestSignInPrompt => ResourceManager.GetString("RequestSignInPrompt", resourceCulture);
        public static string RequestFormTitle => ResourceManager.GetString("RequestFormTitle", resourceCulture);
        public static string RequestFormDescription => ResourceManager.GetString("RequestFormDescription", resourceCulture);
        public static string RequestSuccessTitle => ResourceManager.GetString("RequestSuccessTitle", resourceCulture);
        public static string RequestSuccessBody => ResourceManager.GetString("RequestSuccessBody", resourceCulture);
        public static string CompanyNameLabel => ResourceManager.GetString("CompanyNameLabel", resourceCulture);
        public static string VenueNameLabel => ResourceManager.GetString("VenueNameLabel", resourceCulture);
        public static string ContactNameLabel => ResourceManager.GetString("ContactNameLabel", resourceCulture);
        public static string ContactEmailLabel => ResourceManager.GetString("ContactEmailLabel", resourceCulture);
        public static string ContactPhoneLabel => ResourceManager.GetString("ContactPhoneLabel", resourceCulture);
        public static string CityLabel => ResourceManager.GetString("CityLabel", resourceCulture);
        public static string CountryLabel => ResourceManager.GetString("CountryLabel", resourceCulture);
        public static string AddressLabel => ResourceManager.GetString("AddressLabel", resourceCulture);
        public static string EstimatedMonthlyBookingsLabel => ResourceManager.GetString("EstimatedMonthlyBookingsLabel", resourceCulture);
        public static string NotesLabel => ResourceManager.GetString("NotesLabel", resourceCulture);
        public static string RequestHelperText => ResourceManager.GetString("RequestHelperText", resourceCulture);
        public static string SubmitRequestCta => ResourceManager.GetString("SubmitRequestCta", resourceCulture);
        public static string RequestSidebarTitle => ResourceManager.GetString("RequestSidebarTitle", resourceCulture);
        public static string RequestSidebarBody => ResourceManager.GetString("RequestSidebarBody", resourceCulture);
        public static string AuthLoginTitle => ResourceManager.GetString("AuthLoginTitle", resourceCulture);
        public static string AuthLoginEyebrow => ResourceManager.GetString("AuthLoginEyebrow", resourceCulture);
        public static string AuthLoginHeadline => ResourceManager.GetString("AuthLoginHeadline", resourceCulture);
        public static string AuthLoginDescription => ResourceManager.GetString("AuthLoginDescription", resourceCulture);
        public static string AuthRegisterTitle => ResourceManager.GetString("AuthRegisterTitle", resourceCulture);
        public static string AuthRegisterEyebrow => ResourceManager.GetString("AuthRegisterEyebrow", resourceCulture);
        public static string AuthRegisterHeadline => ResourceManager.GetString("AuthRegisterHeadline", resourceCulture);
        public static string AuthRegisterDescription => ResourceManager.GetString("AuthRegisterDescription", resourceCulture);
        public static string AuthPanelStatOne => ResourceManager.GetString("AuthPanelStatOne", resourceCulture);
        public static string AuthPanelStatTwo => ResourceManager.GetString("AuthPanelStatTwo", resourceCulture);
        public static string AuthPanelStatThree => ResourceManager.GetString("AuthPanelStatThree", resourceCulture);
        public static string LoginHeading => ResourceManager.GetString("LoginHeading", resourceCulture);
        public static string LoginBody => ResourceManager.GetString("LoginBody", resourceCulture);
        public static string RegisterHeading => ResourceManager.GetString("RegisterHeading", resourceCulture);
        public static string RegisterBody => ResourceManager.GetString("RegisterBody", resourceCulture);
        public static string EmailLabel => ResourceManager.GetString("EmailLabel", resourceCulture);
        public static string PasswordLabel => ResourceManager.GetString("PasswordLabel", resourceCulture);
        public static string ConfirmPasswordLabel => ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
        public static string RememberMeLabel => ResourceManager.GetString("RememberMeLabel", resourceCulture);
        public static string LoginButton => ResourceManager.GetString("LoginButton", resourceCulture);
        public static string RegisterButton => ResourceManager.GetString("RegisterButton", resourceCulture);
        public static string SwitchToRegister => ResourceManager.GetString("SwitchToRegister", resourceCulture);
        public static string SwitchToLogin => ResourceManager.GetString("SwitchToLogin", resourceCulture);
        public static string RequiredField => ResourceManager.GetString("RequiredField", resourceCulture);
        public static string InvalidEmailAddress => ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
        public static string MonthlyBookingsRange => ResourceManager.GetString("MonthlyBookingsRange", resourceCulture);
        public static string PasswordMismatch => ResourceManager.GetString("PasswordMismatch", resourceCulture);
    }
}
