//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views.Shop {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {

        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() { }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    resourceMan = new System.Resources.ResourceManager("App.Resources.Views.Shop.Index", typeof(Index).Assembly);
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string Filter { get { return ResourceManager.GetString("Filter", resourceCulture); } }
        public static string Category { get { return ResourceManager.GetString("Category", resourceCulture); } }
        public static string Collection { get { return ResourceManager.GetString("Collection", resourceCulture); } }
        public static string Gender { get { return ResourceManager.GetString("Gender", resourceCulture); } }
        public static string All { get { return ResourceManager.GetString("All", resourceCulture); } }
        public static string Products { get { return ResourceManager.GetString("Products", resourceCulture); } }
        public static string NoProducts { get { return ResourceManager.GetString("NoProducts", resourceCulture); } }
        public static string From { get { return ResourceManager.GetString("From", resourceCulture); } }
    }
}
